//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Project_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public System.Guid BookingId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime BookDateFrom { get; set; }
        public System.DateTime BookDateTo { get; set; }
        public System.Guid HotelId { get; set; }
        public int Rooms { get; set; }
        public int PersonsStay { get; set; }
    }
}
