//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Project_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Continent
    {
        public System.Guid ContinentId { get; set; }
        public string ContinentName { get; set; }
        public string ContinentDescription { get; set; }
        public string ContinentCode { get; set; }
    }
}
