//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Project_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public System.Guid CountryId { get; set; }
        public string CountryName { get; set; }
        public string CountryDescription { get; set; }
        public System.Guid ContinentId { get; set; }
        public string CountryCode { get; set; }
    }
}
