//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Project_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public System.Guid FoodId { get; set; }
        public string FoodName { get; set; }
        public int FoodType { get; set; }
        public System.Guid HotelId { get; set; }
    }
}
