//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Project_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public System.Guid HotelId { get; set; }
        public string HotelName { get; set; }
        public string HotelDescription { get; set; }
        public System.Guid CountryId { get; set; }
        public int StarRating { get; set; }
        public bool IsDeleted { get; set; }
        public string HotelCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> Wifi { get; set; }
        public Nullable<bool> Spa { get; set; }
        public Nullable<bool> Pool { get; set; }
    }
}
